const ROLE_USER = {
  USER: "USER",
  EDITOR: "EDITOR",
  ADMIN: "ADMIN",
};

const FRIEND_STATUS = {
  FOLLOW: "FOLLOW",
  FRIEND: "FRIEND",
  UNFRIEND: "UNFRIEND",
}
module.exports = { ROLE_USER, FRIEND_STATUS };
