const POST_STATUS_TYPES = {
  PUBLIC_POST: "PUBLIC",
  PRIVATE_POST: "PRIVATE",
  FRIEND_POST: "FRIEND",
  GET_ALL: "ALL",
};

const POST_IMAGE_CATEGORY = {
  NORMAL_IAMGE: "NORMAL",
  AVATAR_IAMGE: "AVATAR",
  COVER_IAMGE: "COVER",
  GET_ALL: "ALL",
};

const LIKE_CATEGORY = {
    LIKE: "LIKE",
    LOVE: "LOVE",
    HAHA: "HAHA",
    SAD: "SAD",
    ANGRY: "ANGRY",
    GET_ALL: "ALL",
  };
  

module.exports = { POST_STATUS_TYPES, POST_IMAGE_CATEGORY, LIKE_CATEGORY };
